name: Build and Push Docker Image to DockerHub

on:
  push:
    branches: [ master ] # Executa somente em pushes para o branch 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Usa uma máquina virtual Ubuntu
    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Faz o login no Docker Hub usando os secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Constrói a imagem e envia para o Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .      # O contexto é a raiz do repositório
          push: true      # A instrução para ENVIAR (push) a imagem
          tags: dalexperia/n-queue-mode:latest # O nome e tag da sua imagem